/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  collections: {
    articles: Article
    posts: Post
    tags: Tag
    media: Media
    users: User
  }
  collectionsJoins: {}
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>
    posts: PostsSelect<false> | PostsSelect<true>
    tags: TagsSelect<false> | TagsSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    users: UsersSelect<false> | UsersSelect<true>
  }
  db: {
    defaultIDType: number
  }
  globals: {}
  globalsSelect: {}
  locale: null
  user: User & {
    collection: 'users'
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}

export interface Article {
  id: number
  title: string
  slug: string
  content: any
  excerpt?: string | null
  featureImage?: (number | null) | Media
  tags?: (number | Tag)[] | null
  status?: ('draft' | 'published') | null
  publishedAt?: string | null
  metaDescription?: string | null
  updatedAt: string
  createdAt: string
}

export interface Post {
  id: number
  title: string
  slug: string
  content: unknown
  excerpt?: string | null
  featureImage?: (number | null) | Media
  tags?: (number | Tag)[] | null
  status?: ('draft' | 'published') | null
  publishedAt?: string | null
  readingTime?: number | null
  metaDescription?: string | null
  updatedAt: string
  createdAt: string
}

export interface PostsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  content?: T
  excerpt?: T
  featureImage?: T
  tags?: T
  status?: T
  publishedAt?: T
  readingTime?: T
  metaDescription?: T
  updatedAt?: T
  createdAt?: T
}

export interface Media {
  id: number
  alt: string
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    card?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    hero?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
}

export interface Tag {
  id: number
  name: string
  slug: string
  updatedAt: string
  createdAt: string
}

export interface User {
  id: number
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
}

export interface ArticlesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  content?: T
  excerpt?: T
  featureImage?: T
  tags?: T
  status?: T
  publishedAt?: T
  metaDescription?: T
  updatedAt?: T
  createdAt?: T
}

export interface TagsSelect<T extends boolean = true> {
  name?: T
  slug?: T
  updatedAt?: T
  createdAt?: T
}

export interface MediaSelect<T extends boolean = true> {
  alt?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
  sizes?: T
}

export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
}
